export const themes = {
  "light": {
      color: "#282230",       
      background: "#f1f1f1",  
      primary: "#005080",
      "primary-text": "#a5e0cf",
      secondary: "#499CBA",
      positive: "green",      
      "positive-text": "#f1f1f1",
      negative: "red",        
      error: "#FE2E64",       
      warning: "#FFBF00",     
      info: "#81F7D8",
  },
  "dark":{
      color: "#f1f1f1",
      background: "#27323a",
      primary: "#005080",
      "primary-text": "#a5e0cf",
      secondary: "#499CBA",
      positive: "green",
      negetive: "red",
      error: "#CC0000",
      warning: "#884400",     
      info: "#00ccAA",
  },
  "blue": {
    color: "#363737",
    background: "#acfffc",
    primary: "#0d75f8",
    secondary: "#499CBA",
    positive: "green",
    negetive: "pink",
    error: "#CC0000",
    warning: "#884400",     
    info: "#00ccAA",
  },
  "autumn":{
    color: "red",
    background: "orange",
    primary: "#880022",
    "primary-text": "#CC2200",
    secondary: "#499CBA",
    positive: "green",
    negetive: "pink",
    error: "#CC0000",
    warning: "#884400",     
    info: "#00ccAA",
  }
};
